service: aws-sdk-s3-evan

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  dig:
    handler: lambdas/dig.dig
    events:
      - http:
          path: hole
          method: get
          cors: true